@echo off
REM $Id: configure-bcc.bat,v 1.1.1.1 2002/11/03 19:18:16 hmichelon Exp $
echo Borland C++ 5.5 configure script
if "%1" == "" goto err_usage
if "%2" == "" goto generate
if "%2" == "release" goto generate
if "%2" == "debug" goto generate

REM -----------------------------
:err_usage
echo Usage: configure-bcc nmo_directory [buildmode]
echo where 'buildmode' is 'release' (default) or 'debug'
goto end


REM -----------------------------
:generate
echo Generating Makefile.bcc.mk...
echo # File generated by configure-bcc.bat > Makefile.bcc.mk
echo # edit configure-bcc.bat, >> Makefile.bcc.mk
echo #      build\Windows\BCC\Makefile.bcc, >> Makefile.bcc.mk
echo #      or build\Windows\BCC\Makefile. >> Makefile.bcc.mk
echo # and re-run configure-bcc.bat >> Makefile.bcc.mk
echo NMODIR=%1 >> Makefile.bcc.mk
if "%2" == "debug" echo DEBUG=1 >> Makefile.bcc.mk
type build\Windows\BCC\Makefile.bcc >> Makefile.bcc.mk

echo Generating Makefile...
echo # File generated by configure-bcc.bat > Makefile
echo # edit configure-bcc.bat, >> Makefile
echo #      build\Windows\BCC\Makefile.bcc, >> Makefile
echo #      or build\Windows\BCC\Makefile. >> Makefile
echo # and re-run configure-bcc.bat >> Makefile
type build\Windows\BCC\Makefile >> Makefile
goto end


REM -----------------------------
:end
